# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e3f0e4e1cfe9bde54085f218b1add32e408dc6e4688f6f6049f3b0278945847d547f82ceb78168669653846c060e30aaf33e7c3d54b0518175fd8427a441f1

test:
  secret_key_base: 105415a56f6365ed17f856a884ed885f34217b9a1da35493d1de0b2631075f68df61b923887937d143b58db6b21a4562342e063899469dde03e628e8bc0fa5e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
